# Generated by Django 6.1 on 2026-10-06 02:14

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('HABILITADA', 'Habilitada'), ('DESHABILITADA', 'Deshabilitada')], default='HABILITADA', max_length=13)),
                ('creado_por_keycloak_id', models.CharField(editable=False, max_length=255)),
                ('creado_por_username', models.CharField(blank=True, editable=False, max_length=150)),
                ('actualizado_por_keycloak_id', models.CharField(editable=False, max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('codigo',),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Upper('codigo'), name='caja_codigo_unico'), models.CheckConstraint(condition=models.Q(('codigo', ''), _negated=True), name='caja_codigo_no_vacio'), models.CheckConstraint(condition=models.Q(('nombre', ''), _negated=True), name='caja_nombre_no_vacio'), models.CheckConstraint(condition=models.Q(('estado__in', ['HABILITADA', 'DESHABILITADA'])), name='caja_estado_valido')],
            },
        ),
    ]
