# Generated by Django 6.1 on 2026-10-06 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0001_initial'),
        ('monedas', '0002_monedas_iniciales'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=7)),
                ('responsable_keycloak_id', models.CharField(editable=False, max_length=255)),
                ('responsable_username', models.CharField(blank=True, editable=False, max_length=150)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodos', to='cajas.caja')),
            ],
            options={
                'ordering': ('-fecha_apertura',),
            },
        ),
        migrations.CreateModel(
            name='SaldoInicialCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=6, max_digits=18)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos_iniciales_caja', to='monedas.moneda')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos_iniciales', to='cajas.periodocaja')),
            ],
            options={
                'ordering': ('moneda__codigo',),
            },
        ),
        migrations.AddConstraint(
            model_name='periodocaja',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ABIERTO')), fields=('caja',), name='caja_unico_periodo_abierto'),
        ),
        migrations.AddConstraint(
            model_name='periodocaja',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['ABIERTO', 'CERRADO'])), name='periodo_caja_estado_valido'),
        ),
        migrations.AddConstraint(
            model_name='saldoinicialcaja',
            constraint=models.UniqueConstraint(fields=('periodo', 'moneda'), name='saldo_inicial_periodo_moneda_unico'),
        ),
        migrations.AddConstraint(
            model_name='saldoinicialcaja',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gte', 0)), name='saldo_inicial_no_negativo'),
        ),
    ]
