# Generated by Django 6.1 on 2026-09-04 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monedas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasaComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compra', models.DecimalField(decimal_places=6, max_digits=18)),
                ('venta', models.DecimalField(decimal_places=6, max_digits=18)),
                ('vigente', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('usuario_id', models.CharField(max_length=255)),
                ('usuario_username', models.CharField(blank=True, max_length=150)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('moneda_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasas_destino', to='monedas.moneda')),
                ('moneda_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasas_origen', to='monedas.moneda')),
            ],
            options={
                'ordering': ('-fecha_registro',),
                'constraints': [models.CheckConstraint(condition=models.Q(('moneda_origen', models.F('moneda_destino')), _negated=True), name='tasa_monedas_distintas'), models.UniqueConstraint(condition=models.Q(('vigente', True)), fields=('moneda_origen', 'moneda_destino'), name='una_tasa_vigente_por_par')],
            },
        ),
    ]
