# Generated by Django 6.1 on 2026-10-09 01:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def iniciar_umbral(apps, schema_editor):
    """Persiste el 3 % global aprobado sin alterar configuración existente."""
    apps.get_model('tasas', 'ConfiguracionNotificacionTasa').objects.using(schema_editor.connection.alias).get_or_create(
        pk=1, defaults={'umbral_porcentaje': Decimal('3')},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0002_monedas_iniciales'),
        ('tasas', '0003_tasacomercial_precision'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNotificacionTasa',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('umbral_porcentaje', models.DecimalField(decimal_places=10, default=Decimal('3'), max_digits=24)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='notificacion_config_unica'), models.CheckConstraint(condition=models.Q(('umbral_porcentaje__gt', 0)), name='notificacion_umbral_positivo')],
            },
        ),
        migrations.CreateModel(
            name='EventoNotificacionTasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compra_anterior', models.DecimalField(decimal_places=10, max_digits=24, null=True)),
                ('venta_anterior', models.DecimalField(decimal_places=10, max_digits=24, null=True)),
                ('umbral_porcentaje', models.DecimalField(decimal_places=10, max_digits=24)),
                ('procesado', models.BooleanField(default=False)),
                ('error_destinatarios', models.CharField(blank=True, max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('tasa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='evento_notificacion', to='tasas.tasacomercial')),
            ],
        ),
        migrations.CreateModel(
            name='BaseNotificacionTasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario_id', models.CharField(max_length=255)),
                ('compra', models.DecimalField(decimal_places=10, max_digits=24)),
                ('venta', models.DecimalField(decimal_places=10, max_digits=24)),
                ('moneda_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bases_notificacion_destino', to='monedas.moneda')),
                ('moneda_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bases_notificacion_origen', to='monedas.moneda')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('destinatario_id', 'moneda_origen', 'moneda_destino'), name='base_notificacion_usuario_par_unica')],
            },
        ),
        migrations.CreateModel(
            name='ResultadoNotificacionTasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario_id', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('SIN_CAMBIOS', 'Sin cambios relevantes'), ('ENVIADO', 'Aceptado por correo'), ('FALLIDO', 'Fallido')], default='EN_PROCESO', max_length=11)),
                ('cambios', models.JSONField(default=list)),
                ('error', models.CharField(blank=True, max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='tasas.eventonotificaciontasa')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('evento', 'destinatario_id'), name='notificacion_evento_usuario_unica'), models.CheckConstraint(condition=models.Q(('estado__in', ['EN_PROCESO', 'SIN_CAMBIOS', 'ENVIADO', 'FALLIDO'])), name='notificacion_resultado_estado_valido')],
            },
        ),
        migrations.RunPython(iniciar_umbral, migrations.RunPython.noop),
    ]
