# Generated by Django 6.1 on 2026-09-27 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_cliente_metodo_pago_preferido'),
        ('metodos_pago', '0002_catalogo_global'),
        ('monedas', '0002_monedas_iniciales'),
        ('tasas', '0002_tasacomercial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_idempotencia', models.CharField(max_length=255, unique=True)),
                ('creado_por_keycloak_id', models.CharField(max_length=255)),
                ('creado_por_username', models.CharField(blank=True, default='', max_length=150)),
                ('tipo', models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta')], max_length=10)),
                ('monto_origen', models.DecimalField(decimal_places=6, max_digits=18)),
                ('monto_destino', models.DecimalField(decimal_places=6, max_digits=18)),
                ('tasa_aplicada', models.DecimalField(decimal_places=6, max_digits=18)),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, max_digits=5)),
                ('importe_comision', models.DecimalField(decimal_places=6, max_digits=18)),
                ('metodo_pago_nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=10)),
                ('cancelado_por_keycloak_id', models.CharField(blank=True, max_length=255, null=True)),
                ('cancelado_por_username', models.CharField(blank=True, max_length=150, null=True)),
                ('cancelado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelacion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='clientes.cliente')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='metodos_pago.metodopago')),
                ('moneda_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_destino', to='monedas.moneda')),
                ('moneda_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_origen', to='monedas.moneda')),
                ('tasa_comercial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='tasas.tasacomercial')),
            ],
            options={
                'verbose_name': 'transacción',
                'verbose_name_plural': 'transacciones',
                'ordering': ('-fecha_creacion',),
                'constraints': [models.CheckConstraint(condition=models.Q(('moneda_origen', models.F('moneda_destino')), _negated=True), name='transaccion_monedas_distintas'), models.CheckConstraint(condition=models.Q(('monto_origen__gt', 0)), name='transaccion_monto_origen_positivo'), models.CheckConstraint(condition=models.Q(('monto_destino__gt', 0)), name='transaccion_monto_destino_positivo'), models.CheckConstraint(condition=models.Q(('tasa_aplicada__gt', 0)), name='transaccion_tasa_aplicada_positiva'), models.CheckConstraint(condition=models.Q(('porcentaje_comision__gte', 0)), name='transaccion_comision_no_negativa'), models.CheckConstraint(condition=models.Q(('porcentaje_comision__lte', 100)), name='transaccion_comision_maxima_100'), models.CheckConstraint(condition=models.Q(('importe_comision__gte', 0)), name='transaccion_importe_comision_no_negativo'), models.CheckConstraint(condition=models.Q(models.Q(('estado', 'CANCELADA'), _negated=True), models.Q(('cancelado_por_keycloak_id__isnull', False), ('cancelado_por_username__isnull', False), ('cancelado_en__isnull', False), ('motivo_cancelacion__isnull', False), models.Q(('motivo_cancelacion', ''), _negated=True)), _connector='OR'), name='transaccion_cancelada_con_datos'), models.CheckConstraint(condition=models.Q(models.Q(('estado', 'PENDIENTE'), _negated=True), models.Q(('cancelado_por_keycloak_id__isnull', True), ('cancelado_por_username__isnull', True), ('cancelado_en__isnull', True), ('motivo_cancelacion__isnull', True)), _connector='OR'), name='transaccion_pendiente_sin_cancelacion')],
            },
        ),
    ]
